# site properties and page defaults
title: FoodCODE
subtitle: A Monash Addiction & Impulsivity research study
description: <ul>We are a neuroscience research group with the Turner Institute for Brain and Mental Health at Monash University, led by Professor Antonio Verdejo-Garcia.</ul>
<ul>Our mission is to generate neuroscience knowledge and create evidence-based tools that help improve the quality of life for people with addictive & eating/weight disorders. </ul>
<ul>We envisage a future where people with a living experience of addictive and eating/weight disorders feel empowered to make choices that are fully aligned with their well-being goals.</ul>
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: foodcode@monash.edu
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: airlabmonash
  twitter: airlabmonash
  youtube: airlabmonash

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
